### ISSUE TITLE
Error when running Svelte Table basic example

### ISSUE THREAD

**Issue by dlamon1** [TanStack/table#4420]
### Describe the bug

Copying and pasting the Svelte Table Basic example into my own project throws the following error: 

`index.js:1890 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$$')
    at Object.init (index.js:1890:50)
    at new <anonymous> (index.production.js:21:44094)
    at create_if_block_1 (Shows2.svelte:111:38)
    at create_each_block_5 (Shows2.svelte:107:41)
    at create_each_block_4 (Shows2.svelte:105:17)
    at create_fragment$2 (Shows2.svelte:103:13)
    at init (index.mjs:1907:37)
    at new Shows2 (Shows2.svelte:153:35)
    at Array.create_default_slot_2 (Router.svelte:23:28)
    at create_slot (index.mjs:69:29)`

### Your minimal, reproducible example

I don't have a link, sorry

### Steps to reproduce

Copy Basic Table

### Expected behavior

Expected behavior is to work as does on codesandbox

### Platform

macOS v12.3, Chrome Version 105.0.5195.125

### react-table version

latest

### TypeScript version

4.8.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Sorry, but with no reproducible sandbox, we can only assume that you have something wrong with your dependencies or vite config. All the svelte examples on the website are working fine, so going to close this. If anyone can reproduce and share, it can be re-opened.
