### ISSUE TITLE
Error: semantic error TS2305: Module '"../node_modules/@tanstack/react-table/build/types"' has no exported member 'ColumnDef'.

### ISSUE THREAD

**Issue by killouis** [TanStack/table#4459]
### Describe the bug

I'm trying to build a UI library. When I import "ColumnDef" from "@tanstack/react-table", I receve this error:

```
$ tsdx build
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to 'true', as the next major version will default this option to 'true'.
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to 'true', as the next major version will default this option to 'true'.
✓ Creating entry file 2.1 secs
(typescript) Error: C:/.../src/DataTable.tsx(21,3): semantic error TS2305: Module '"../node_modules/@tanstack/react-table/build/types"' has no exported member 'ColumnDef'.
Error: C:/.../src/DataTable.tsx(21,3): semantic error TS2305: Module '"../node_modules/@tanstack/react-table/build/types"' has no exported member 'ColumnDef'.
    at error (C:\...\node_modules\rollup\dist\shared\node-entry.js:5400:30)
    at throwPluginError (C:\...\node_modules\rollup\dist\shared\node-entry.js:11878:12)
    at Object.error (C:\...\node_modules\rollup\dist\shared\node-entry.js:12912:24)
    at Object.error (C:\...\rollup\dist\shared\node-entry.js:12081:38)
    at RollupContext.error (C:\...\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:17237:30)
    at C:\...\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:25033:23
    at arrayEach (C:\...\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:545:11)
    at Function.forEach (C:\...\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:9397:14)
    at printDiagnostics (C:\...\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:25006:12)
    at Object.transform (C:\...\node_modules\tsdx\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:29277:17)
    at C:\...\node_modules\rollup\dist\shared\node-entry.js:13117:25     
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Everything works in development, it just fails the build. In my component I import the type definition like this:
```
import {
  ColumnDef,
  flexRender,
  getCoreRowModel,
  getSortedRowModel,
  SortingState,
  useReactTable,
} from '@tanstack/react-table';
```

This is my tsconfig.json
```
{
    "include": ["src", "@types"],
    "compilerOptions": {
      "module": "esnext",
      "lib": ["dom", "esnext"],
      "importHelpers": true,
      "declaration": true,
      "sourceMap": true,
      "rootDir": "./src",
      "strict": true,
      "noImplicitReturns": true,
      "noImplicitAny": false,
      "noFallthroughCasesInSwitch": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "moduleResolution": "node",
      "jsx": "react",
      "esModuleInterop": true,
      "skipLibCheck": true,
      "forceConsistentCasingInFileNames": true,
      "noEmit": true
    }
}
```

### Your minimal, reproducible example

https://codesandbox.io/s/new

### Steps to reproduce

 Build with imports above using tsdx.

### Expected behavior

The build works

### Platform

Windows 11

### react-table version

8.5.15

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by dev-gscwd** [comment]
I can confirm that I'm having similar error when trying to build with TSDX. I also have the version 8.5.15

**Comment by MFWBD** [comment]
I actually just came here to deal with this error

**Comment by KevinVandy** [comment]
> I can confirm that I'm having similar error when trying to build with TSDX. I also have the version 8.5.15

I can confirm that TSDX's version of typescript is too outdated to work with this library. I originally used TSDX with `@tanstack-table/react` successfully all the way through version 8.2 of Tanstack table, but now TypeScript v 4.7 or so is the minimum required because of the DeepKeys ts features that were implemented. 

The only solution is to use your own rollup config, which is not as hard as it used to be.

Something like this will suffice

```js
//rollup.config
import external from 'rollup-plugin-peer-deps-external';
import resolve from '@rollup/plugin-node-resolve';
import typescript from '@rollup/plugin-typescript';
import { babel } from '@rollup/plugin-babel';

export default [
  {
    external: [
      '@tanstack/react-table',
      'react',
      //etc.
    ],
    input: './src/index.tsx',
    output: [
      {
        file: './dist/cjs/index.js',
        format: 'cjs',
        sourcemap: true,
      },
      {
        file: './dist/esm/material-react-table.esm.js',
        format: 'esm',
        sourcemap: true,
      },
    ],
    plugins: [
      babel({
        exclude: 'node_modules/**',
        presets: ['@babel/preset-react'],
      }),
      external(),
      resolve(),
      typescript(),
    ],
  },
]

```

**Comment by cscovino** [comment]
I'm getting this issue with `"@tanstack/react-table": "^8.5.27"`. I'm using build tool `vite`

**Comment by cscovino** [comment]
Actually, the problem is when I try to type `ColumnMeta` following the docs:

```
declare module '@tanstack/table-core' {
  interface ColumnMeta<TData extends RowData, TValue> {
    foo: string
  }
}
```

I have to add the first line to make it works:
```
import { ColumnMeta } from '@tanstack/react-table';

declare module '@tanstack/table-core' {
  interface ColumnMeta<TData extends RowData, TValue> {
    isNumeric: boolean;
  }
}

```

**Comment by goamn** [comment]
@killouis Had the same error and finally fixed it. I updated my typescript and now it's working with the following versions:
> "@tanstack/react-table": "8.5.28",
> "typescript": "4.8.4",

**Comment by mattleonowicz** [comment]
Somehow in my case, my import was being deleted when I saved the file, probably IDE recognized "unused" import and deleted that. I did import `RowData` though, because it's actually used in this declaration. IDE didnt delete that, and it also worked. I think maybe anything from `@tanstack/react-table` has to be imported? 
```
import type { RowData } from '@tanstack/react-table';

declare module '@tanstack/table-core' {
  interface ColumnMeta<TData extends RowData, TValue> {
    align?: 'right';
  }
}
```
