### ISSUE TITLE
Running test with cypress fails because webpack can't bundle react-table

### ISSUE THREAD

**Issue by MAST1999** [TanStack/table#4501]
### Describe the bug

When I try to run the E2E test with cypress, when I get to a page with table in it I encounter this error:

```
Error: Webpack Compilation Error
./node_modules/@tanstack/react-table/build/umd/index.production.js 21:1014
Module parse failed: Unexpected token (21:1014)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|    *
|    * @license MIT
>    */function l(e,t){return"function"==typeof e?e(t):e}function i(e,t){return n=>{t.setState((t=>({...t,[e]:l(n,t[e])})))}}function r(e){return e instance
....
e},onStateChange:t=>{i(t),null==e.onStateChange||e.onStateChange(t)}}))),n.current},Object.defineProperty(e,"__esModule",{value:!0})}));
| //# sourceMappingURL=index.production.js.map
| 
 @ ./src/components/utility.js 16:18-50
 @ ./cypress/e2e/plant/test_new_plant.js
    at Watching.handle [as handler] (/home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:180:23)
    at /home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/webpack/lib/Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/webpack/lib/Watching.js:98:28)
    at /home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/webpack/lib/Watching.js:73:19
    at Compiler.emitRecords (/home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/webpack/lib/Watching.js:54:20
    at /home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/neo-async/async.js:2818:7
    at done (/home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/mast/.cache/Cypress/10.7.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23)
```

I can build locally with `npm run build` but I don't know why when using cypress, webpack fails to bundle things.

### Your minimal, reproducible example

I don't have a reproducible example to share.

### Steps to reproduce

Run a test with `@tanstack/react-table` inside the page and it will fail.

### Expected behavior

Webpack bundles react-table and cypress runs the test.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/48868969/199527811-fdd40853-b537-497a-893b-a01cba95cae4.png)

### Platform

Linux

### react-table version

8.5.22

### TypeScript version

none

### Additional context

I tried using the latest version of cypress but it made no difference.

This is the cypress settings:

```JavaScript
const { defineConfig } = require('cypress');

module.exports = defineConfig({
  projectId: 'onqmuc',
  viewportHeight: 1080,
  viewportWidth: 1920,
  video: false,
  scrollBehavior: 'center',
  e2e: {
    baseUrl: 'http://localhost:3000/#/',
    specPattern: 'cypress/e2e/**/*',
    setupNodeEvents(on, config) {
      on('task', {
        testTimings(attributes) {
          console.log('Test "%s" has finished in %dms', attributes.title, attributes.duration);
          console.table(attributes.commands);
          return null;
        },
      });

      // implement node event listeners here
      require('@cypress/code-coverage/task')(on, config)
    
      // It's IMPORTANT to return the config object
      // with any changed environment variables
      return config
    },
  },
  reporter: 'cypress-multi-reporters',
  reporterOptions: {
    configFile: 'reporter-config.json',
  },
```

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by MAST1999** [comment]
Hey

I managed to fix it by changing the cypress config to this:

```JavaScript
const { defineConfig } = require('cypress');
const webpackPreprocessor = require('@cypress/webpack-preprocessor');

module.exports = defineConfig({
  projectId: 'onqmuc',
  viewportHeight: 1080,
  viewportWidth: 1920,
  video: false,
  scrollBehavior: 'center',
  e2e: {
    baseUrl: 'http://localhost:3000/#/',
    specPattern: 'cypress/e2e/**/*',
    setupNodeEvents(on, config) {
      on('task', {
        testTimings(attributes) {
          console.log('Test "%s" has finished in %dms', attributes.title, attributes.duration);
          console.table(attributes.commands);
          return null;
        },
      });

      let options = webpackPreprocessor.defaultOptions
      options.webpackOptions.module.rules[0].use[0].options.presets.push('@babel/preset-react')
      on('file:preprocessor', webpackPreprocessor(options));

      // implement node event listeners here
      require('@cypress/code-coverage/task')(on, config);

      // It's IMPORTANT to return the config object
      // with any changed environment variables
      return config;
    },
  },
  reporter: 'cypress-multi-reporters',
  reporterOptions: {
    configFile: 'reporter-config.json',
  },
});
```

I basically told webpack to use `@babel/preset-react` and it worked.

But I'll leave this open for now for comments, If you guys think this is good enough then we can close this issue.

**Comment by KevinVandy** [comment]
@MAST1999 Try out the newest TanStack Table `v8.7.0` and let us know if you are still running into problems here

We think PR https://github.com/TanStack/table/pull/4552 should have fixed this issue.

**Comment by MAST1999** [comment]
Hi, sorry for the delay.

I checked with the newest version and it does indeed work!

Thanks for the hard work!
