### ISSUE TITLE
Simple table throws `Cannot read properties of undefined (reading 'length')` when using `getRowModel()` in v8.9.1

### ISSUE THREAD

**Issue by KerimG** [TanStack/table#4869]
### Describe the bug

I'm trying use react-table for a simple 2 column table in its most basic form following the [basic example](https://tanstack.com/table/v8/docs/examples/react/basic), or rather the JS variant [here](https://stackoverflow.com/questions/73885732/how-to-implement-react-table-without-typescript). However `table.getRowModel()` consistently throws the following error:

```
ERROR
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at accessRows (http://localhost:3000/static/js/bundle.js:54966:40)
    at memo.key (http://localhost:3000/static/js/bundle.js:54997:21)
    at Object._getCoreRowModel (http://localhost:3000/static/js/bundle.js:52051:14)
    at Object.getCoreRowModel (http://localhost:3000/static/js/bundle.js:54670:20)
    at Object.getPreFilteredRowModel (http://localhost:3000/static/js/bundle.js:53170:43)
    at Object.getFilteredRowModel (http://localhost:3000/static/js/bundle.js:53176:24)
    at Object.getPreGroupedRowModel (http://localhost:3000/static/js/bundle.js:53379:42)
    at Object.getGroupedRowModel (http://localhost:3000/static/js/bundle.js:53385:24)
    at Object.getPreSortedRowModel (http://localhost:3000/static/js/bundle.js:54475:41)
    at Object.getSortedRowModel (http://localhost:3000/static/js/bundle.js:54481:24)
```

### Your minimal, reproducible example

https://codesandbox.io/s/crazy-bird-bevdz3?file=/src/App.js

### Steps to reproduce

When running the sanebox, the error should appear immediately.

### Expected behavior

I expected to see a very simple table with the headers rendered to appear. That actually does work if I remove the `console.log` line but then trying to access the rowmodel in the JSX naturally throws the same errro.

### How often does this bug happen?

Every time

### Platform

macOS, Chrome, Firefox
Windows, Chrome

### react-table version

v8.9.1

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by archiesage** [comment]
On first glance, looks like `data` property is missing on `useReactTable` hook.

To fix, it should be:

```
const table = useReactTable({
    data: activeJobs,
    columns,
    getCoreRowModel: getCoreRowModel()
  });
```
Instead of
```
const table = useReactTable({
    activeJobs,
    columns,
    getCoreRowModel: getCoreRowModel()
  });
```

**Comment by KerimG** [comment]
Oh nooo. So embarrassing!! Thank you @archiesage
