### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by genesiscz** [TanStack/table#4966]
### Describe the bug

Most (if not all) codesandbox examples are giving me an error 

- https://tanstack.com/table/v8/docs/examples/react/column-groups

![image](https://github.com/TanStack/table/assets/1512353/9f84db72-8ff7-439c-9c36-26321e22e683)

When I open the editor and open src/main.tsx, it [doesn't load either](https://codesandbox.io/p/sandbox/github/tanstack/table/tree/main/examples/react/column-groups?embed=1&file=%2Fsrc%2Fmain.tsx):

![image](https://github.com/TanStack/table/assets/1512353/64ea773c-a6f9-4ee3-9517-1238f4490bad)

Am I missing something?

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/github/tanstack/table/tree/main/examples/react/column-groups?embed=1&file=%2Fsrc%2Fmain.tsx

### Steps to reproduce

1. Go to documentation or https://codesandbox.io/p/sandbox/github/tanstack/table/tree/main/examples/react/column-groups?embed=1&file=%2Fsrc%2Fmain.tsx for example
2. See the error

### Expected behavior

I expect the code to be shown

### How often does this bug happen?

Every time

### Platform

Windows 11, Brave browser (both (non)anonymous modes)

### react-table version

latest in codesandbox examples

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by radusuciu** [comment]
Pretty sure this is a codesandbox error.

**Comment by baba43** [comment]
I've had this problem for a few days now and it really sucks. The only workaround currently is to find the examples from Github itself.

In my opinion, a project of this size should have decent documentation. Examples are a good and useful addition, but should not replace that basic documentation.

**Comment by parkerault** [comment]
I have this issue too; every example fails in chrome with the following console errors:

```
instrument.js:111 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at 32441 (https://codesandbox.io/p/_next/static/chunks/pages/_app-377e4f13a2cb0af5eb3d.js:1:687235)
    at n (https://codesandbox.io/p/_next/static/chunks/webpack-edabb97e0eb4e1348ea3.js:1:149)
    at 93535 (https://codesandbox.io/p/_next/static/chunks/pages/_app-377e4f13a2cb0af5eb3d.js:1:1087779)
    at n (https://codesandbox.io/p/_next/static/chunks/webpack-edabb97e0eb4e1348ea3.js:1:149)
    at 68801 (https://codesandbox.io/p/_next/static/chunks/pages/_app-377e4f13a2cb0af5eb3d.js:1:717444)
    at n (https://codesandbox.io/p/_next/static/chunks/webpack-edabb97e0eb4e1348ea3.js:1:149)
    at 44397 (https://codesandbox.io/p/_next/static/chunks/pages/_app-377e4f13a2cb0af5eb3d.js:1:727542)
    at n (https://codesandbox.io/p/_next/static/chunks/webpack-edabb97e0eb4e1348ea3.js:1:149)
    at https://codesandbox.io/p/_next/static/chunks/pages/_app-377e4f13a2cb0af5eb3d.js:1:1122142
    at https://codesandbox.io/p/_next/static/chunks/main-f6619ef2246d0489359c.js:1:25202

instrument.js:111 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

config.ts:103 Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at 32441 (https://codesandbox.io/p/_next/static/chunks/pages/_app-377e4f13a2cb0af5eb3d.js:1:687235)
    at n (https://codesandbox.io/p/_next/static/chunks/webpack-edabb97e0eb4e1348ea3.js:1:149)
    at 83024 (https://codesandbox.io/p/_next/static/chunks/pages/_app-377e4f13a2cb0af5eb3d.js:1:675316)
    at n (https://codesandbox.io/p/_next/static/chunks/webpack-edabb97e0eb4e1348ea3.js:1:149)
    at 23399 (https://codesandbox.io/p/_next/static/chunks/pages/_error-748ad78ae893000c6040.js:1:188)
    at n (https://codesandbox.io/p/_next/static/chunks/webpack-edabb97e0eb4e1348ea3.js:1:149)
    at https://codesandbox.io/p/_next/static/chunks/pages/_error-748ad78ae893000c6040.js:1:1492
    at https://codesandbox.io/p/_next/static/chunks/main-f6619ef2246d0489359c.js:1:25202
```
Even if this is a codesandbox error it still needs a workaround in the docs.

IMO documentation has always been sorely lacking for this project, which sucks because I think it's the best approach to complex data grids in the ecosystem, and it makes it difficult to recommend to colleagues when the docs either don't work or just have a sometimes broken link to the API page.

**Comment by sammyzord** [comment]
This library is literally unusable because of the horrible documentation

**Comment by parkerault** [comment]
I just tested the docs and all of the examples appear to be working now, so this issue should probably be closed.
