### ISSUE TITLE
your website is down

### ISSUE THREAD

**Issue by robert-westenberger** [TanStack/table#5512]
### TanStack Table version

n/a

### Framework/Library version

n/a

### Describe the bug and the steps to reproduce it

1. Navigate to https://tanstack.com/table/latest
EXPECTED: It renders
ACTUAL: it doesn't render

Seeing these errors in the browser console

```
client-DDDARTnK.js:542 DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25270)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
client-DDDARTnK.js:38 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25270)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
    at el (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25393)
client-DDDARTnK.js:542 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at tf (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25996)
    at It (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25702)
    at tf (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:26451)
    at It (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25702)
    at tf (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:26451)
    at It (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25702)
    at tf (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:26451)
    at It (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25702)
    at tf (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:26644)
    at It (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25702)
client-DDDARTnK.js:38 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at tf (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25996)
    at It (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25702)
    at tf (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:26451)
    at It (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25702)
    at tf (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:26451)
    at It (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25702)
    at tf (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:26451)
    at It (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25702)
    at tf (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:26644)
    at It (https://tanstack.com/_build/assets/client-DDDARTnK.js:40:25702)
js?id=G-JMT1Z50SPS:641 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at b (js?id=G-JMT1Z50SPS:641:47)
    at js?id=G-JMT1Z50SPS:643:94
    at js?id=G-JMT1Z50SPS:643:269
    at js?id=G-JMT1Z50SPS:650:3
﻿```

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

n/a

### Screenshots or Videos (Optional)

_No response_

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by robert-westenberger** [comment]
Closing this - i now see it rendering.

**Comment by sidpremkumar** [comment]
+1 seeing the same thing here

**Comment by Jarzka** [comment]
+1. 

It seems that the guide pages all crash on Firefox but on in Chrome. See: https://tanstack.com/table/v8/docs/guide/tables

**Comment by zhyd1997** [comment]
+1.

**Comment by sidpremkumar** [comment]
> +1.
> 
> It seems that the guide pages all crash on Firefox but on in Chrome. See: https://tanstack.com/table/v8/docs/guide/tables


Seems like the main website is down 🥳 , but maybe examples are still down. Seeing something similar: https://tanstack.com/table/v7
![2024-05-03 at 1 28 PM](https://github.com/TanStack/table/assets/28202162/f694b49b-0b2f-44ad-a650-d8364cce2901)
